import base64
from odoo import api, fields, models


class AccountMove(models.Model):
    _inherit = "account.move"
    _description = "AccountMove"

    def action_post(self):
        res = super(AccountMove, self).action_post()
        for move in self:
            if move.move_type not in ("out_invoice", "out_refund"):
                continue
            attachment_no = 0
            for line in move.invoice_line_ids:
                if line.display_type == "line_section":
                    attachment_no += 1
                    if line.attachment_id:
                        continue
                    attachment = self.env["ir.attachment"].create({
                        "name": f"{move.name or 'Invoice'} - Attachment {attachment_no}.txt",
                        "type": "binary",
                        "datas": base64.b64encode(
                            b"This is a dummy attachment generated by the system on confirming the Invoice."),
                        "res_model": "account.move",
                        "res_id": move.id,
                        "mimetype": "text/plain",
                    })
                    line.write({
                        "attachment_number": attachment_no,
                        "attachment_id": attachment.id,
                    })

        return res


class AccountMoveLine(models.Model):
    _inherit = "account.move.line"
    _description = "Account Move Line"

    attachment_number = fields.Integer(string="Attachment Number", readonly=True, copy=False)
    attachment_id = fields.Many2one("ir.attachment", string="Attachment", readonly=True, copy=False)
